/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HelloWormholeTest } from "./HelloWormholeTest";
export type { SavingsAccountTest } from "./SavingsAccountTest";
