/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace StdInvariant {
  export type FuzzSelectorStruct = { addr: string; selectors: BytesLike[] };

  export type FuzzSelectorStructOutput = [string, string[]] & {
    addr: string;
    selectors: string[];
  };
}

export interface WormholeRelayerTestInterface extends utils.Interface {
  functions: {
    "CELO_URL()": FunctionFragment;
    "FUJI_URL()": FunctionFragment;
    "IS_TEST()": FunctionFragment;
    "createAndAttestToken(uint256)": FunctionFragment;
    "excludeArtifacts()": FunctionFragment;
    "excludeContracts()": FunctionFragment;
    "excludeSenders()": FunctionFragment;
    "failed()": FunctionFragment;
    "guardianSource()": FunctionFragment;
    "guardianTarget()": FunctionFragment;
    "logFork()": FunctionFragment;
    "performDelivery(uint8)": FunctionFragment;
    "relayerSource()": FunctionFragment;
    "relayerTarget()": FunctionFragment;
    "setUp()": FunctionFragment;
    "setUpSource()": FunctionFragment;
    "setUpTarget()": FunctionFragment;
    "sourceChain()": FunctionFragment;
    "sourceFork()": FunctionFragment;
    "targetArtifactSelectors()": FunctionFragment;
    "targetArtifacts()": FunctionFragment;
    "targetChain()": FunctionFragment;
    "targetContracts()": FunctionFragment;
    "targetFork()": FunctionFragment;
    "targetSelectors()": FunctionFragment;
    "targetSenders()": FunctionFragment;
    "tokenBridgeSource()": FunctionFragment;
    "tokenBridgeTarget()": FunctionFragment;
    "wormholeSource()": FunctionFragment;
    "wormholeTarget()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CELO_URL"
      | "FUJI_URL"
      | "IS_TEST"
      | "createAndAttestToken"
      | "excludeArtifacts"
      | "excludeContracts"
      | "excludeSenders"
      | "failed"
      | "guardianSource"
      | "guardianTarget"
      | "logFork"
      | "performDelivery"
      | "relayerSource"
      | "relayerTarget"
      | "setUp"
      | "setUpSource"
      | "setUpTarget"
      | "sourceChain"
      | "sourceFork"
      | "targetArtifactSelectors"
      | "targetArtifacts"
      | "targetChain"
      | "targetContracts"
      | "targetFork"
      | "targetSelectors"
      | "targetSenders"
      | "tokenBridgeSource"
      | "tokenBridgeTarget"
      | "wormholeSource"
      | "wormholeTarget"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "CELO_URL", values?: undefined): string;
  encodeFunctionData(functionFragment: "FUJI_URL", values?: undefined): string;
  encodeFunctionData(functionFragment: "IS_TEST", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createAndAttestToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "excludeArtifacts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "excludeContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "excludeSenders",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "failed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "guardianSource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "guardianTarget",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "logFork", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "performDelivery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "relayerSource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "relayerTarget",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setUp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setUpSource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setUpTarget",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sourceChain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sourceFork",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetArtifactSelectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetArtifacts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetChain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetFork",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetSelectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "targetSenders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBridgeSource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBridgeTarget",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "wormholeSource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "wormholeTarget",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "CELO_URL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FUJI_URL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IS_TEST", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAndAttestToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludeArtifacts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludeContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludeSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "failed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "guardianSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logFork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relayerSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relayerTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUpSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUpTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sourceChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sourceFork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "targetArtifactSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetArtifacts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "targetFork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "targetSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBridgeSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBridgeTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wormholeSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wormholeTarget",
    data: BytesLike
  ): Result;

  events: {
    "log(string)": EventFragment;
    "log_address(address)": EventFragment;
    "log_array(uint256[])": EventFragment;
    "log_array(int256[])": EventFragment;
    "log_array(address[])": EventFragment;
    "log_bytes(bytes)": EventFragment;
    "log_bytes32(bytes32)": EventFragment;
    "log_int(int256)": EventFragment;
    "log_named_address(string,address)": EventFragment;
    "log_named_array(string,uint256[])": EventFragment;
    "log_named_array(string,int256[])": EventFragment;
    "log_named_array(string,address[])": EventFragment;
    "log_named_bytes(string,bytes)": EventFragment;
    "log_named_bytes32(string,bytes32)": EventFragment;
    "log_named_decimal_int(string,int256,uint256)": EventFragment;
    "log_named_decimal_uint(string,uint256,uint256)": EventFragment;
    "log_named_int(string,int256)": EventFragment;
    "log_named_string(string,string)": EventFragment;
    "log_named_uint(string,uint256)": EventFragment;
    "log_string(string)": EventFragment;
    "log_uint(uint256)": EventFragment;
    "logs(bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "log"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_address"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_array(uint256[])"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_array(int256[])"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_array(address[])"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_address"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "log_named_array(string,uint256[])"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "log_named_array(string,int256[])"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "log_named_array(string,address[])"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "logs"): EventFragment;
}

export interface logEventObject {
  arg0: string;
}
export type logEvent = TypedEvent<[string], logEventObject>;

export type logEventFilter = TypedEventFilter<logEvent>;

export interface log_addressEventObject {
  arg0: string;
}
export type log_addressEvent = TypedEvent<[string], log_addressEventObject>;

export type log_addressEventFilter = TypedEventFilter<log_addressEvent>;

export interface log_array_uint256_array_EventObject {
  val: BigNumber[];
}
export type log_array_uint256_array_Event = TypedEvent<
  [BigNumber[]],
  log_array_uint256_array_EventObject
>;

export type log_array_uint256_array_EventFilter =
  TypedEventFilter<log_array_uint256_array_Event>;

export interface log_array_int256_array_EventObject {
  val: BigNumber[];
}
export type log_array_int256_array_Event = TypedEvent<
  [BigNumber[]],
  log_array_int256_array_EventObject
>;

export type log_array_int256_array_EventFilter =
  TypedEventFilter<log_array_int256_array_Event>;

export interface log_array_address_array_EventObject {
  val: string[];
}
export type log_array_address_array_Event = TypedEvent<
  [string[]],
  log_array_address_array_EventObject
>;

export type log_array_address_array_EventFilter =
  TypedEventFilter<log_array_address_array_Event>;

export interface log_bytesEventObject {
  arg0: string;
}
export type log_bytesEvent = TypedEvent<[string], log_bytesEventObject>;

export type log_bytesEventFilter = TypedEventFilter<log_bytesEvent>;

export interface log_bytes32EventObject {
  arg0: string;
}
export type log_bytes32Event = TypedEvent<[string], log_bytes32EventObject>;

export type log_bytes32EventFilter = TypedEventFilter<log_bytes32Event>;

export interface log_intEventObject {
  arg0: BigNumber;
}
export type log_intEvent = TypedEvent<[BigNumber], log_intEventObject>;

export type log_intEventFilter = TypedEventFilter<log_intEvent>;

export interface log_named_addressEventObject {
  key: string;
  val: string;
}
export type log_named_addressEvent = TypedEvent<
  [string, string],
  log_named_addressEventObject
>;

export type log_named_addressEventFilter =
  TypedEventFilter<log_named_addressEvent>;

export interface log_named_array_string_uint256_array_EventObject {
  key: string;
  val: BigNumber[];
}
export type log_named_array_string_uint256_array_Event = TypedEvent<
  [string, BigNumber[]],
  log_named_array_string_uint256_array_EventObject
>;

export type log_named_array_string_uint256_array_EventFilter =
  TypedEventFilter<log_named_array_string_uint256_array_Event>;

export interface log_named_array_string_int256_array_EventObject {
  key: string;
  val: BigNumber[];
}
export type log_named_array_string_int256_array_Event = TypedEvent<
  [string, BigNumber[]],
  log_named_array_string_int256_array_EventObject
>;

export type log_named_array_string_int256_array_EventFilter =
  TypedEventFilter<log_named_array_string_int256_array_Event>;

export interface log_named_array_string_address_array_EventObject {
  key: string;
  val: string[];
}
export type log_named_array_string_address_array_Event = TypedEvent<
  [string, string[]],
  log_named_array_string_address_array_EventObject
>;

export type log_named_array_string_address_array_EventFilter =
  TypedEventFilter<log_named_array_string_address_array_Event>;

export interface log_named_bytesEventObject {
  key: string;
  val: string;
}
export type log_named_bytesEvent = TypedEvent<
  [string, string],
  log_named_bytesEventObject
>;

export type log_named_bytesEventFilter = TypedEventFilter<log_named_bytesEvent>;

export interface log_named_bytes32EventObject {
  key: string;
  val: string;
}
export type log_named_bytes32Event = TypedEvent<
  [string, string],
  log_named_bytes32EventObject
>;

export type log_named_bytes32EventFilter =
  TypedEventFilter<log_named_bytes32Event>;

export interface log_named_decimal_intEventObject {
  key: string;
  val: BigNumber;
  decimals: BigNumber;
}
export type log_named_decimal_intEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  log_named_decimal_intEventObject
>;

export type log_named_decimal_intEventFilter =
  TypedEventFilter<log_named_decimal_intEvent>;

export interface log_named_decimal_uintEventObject {
  key: string;
  val: BigNumber;
  decimals: BigNumber;
}
export type log_named_decimal_uintEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  log_named_decimal_uintEventObject
>;

export type log_named_decimal_uintEventFilter =
  TypedEventFilter<log_named_decimal_uintEvent>;

export interface log_named_intEventObject {
  key: string;
  val: BigNumber;
}
export type log_named_intEvent = TypedEvent<
  [string, BigNumber],
  log_named_intEventObject
>;

export type log_named_intEventFilter = TypedEventFilter<log_named_intEvent>;

export interface log_named_stringEventObject {
  key: string;
  val: string;
}
export type log_named_stringEvent = TypedEvent<
  [string, string],
  log_named_stringEventObject
>;

export type log_named_stringEventFilter =
  TypedEventFilter<log_named_stringEvent>;

export interface log_named_uintEventObject {
  key: string;
  val: BigNumber;
}
export type log_named_uintEvent = TypedEvent<
  [string, BigNumber],
  log_named_uintEventObject
>;

export type log_named_uintEventFilter = TypedEventFilter<log_named_uintEvent>;

export interface log_stringEventObject {
  arg0: string;
}
export type log_stringEvent = TypedEvent<[string], log_stringEventObject>;

export type log_stringEventFilter = TypedEventFilter<log_stringEvent>;

export interface log_uintEventObject {
  arg0: BigNumber;
}
export type log_uintEvent = TypedEvent<[BigNumber], log_uintEventObject>;

export type log_uintEventFilter = TypedEventFilter<log_uintEvent>;

export interface logsEventObject {
  arg0: string;
}
export type logsEvent = TypedEvent<[string], logsEventObject>;

export type logsEventFilter = TypedEventFilter<logsEvent>;

export interface WormholeRelayerTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WormholeRelayerTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CELO_URL(overrides?: CallOverrides): Promise<[string]>;

    FUJI_URL(overrides?: CallOverrides): Promise<[string]>;

    IS_TEST(overrides?: CallOverrides): Promise<[boolean]>;

    createAndAttestToken(
      fork: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    excludeArtifacts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { excludedArtifacts_: string[] }>;

    excludeContracts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { excludedContracts_: string[] }>;

    excludeSenders(
      overrides?: CallOverrides
    ): Promise<[string[]] & { excludedSenders_: string[] }>;

    failed(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    guardianSource(overrides?: CallOverrides): Promise<[string]>;

    guardianTarget(overrides?: CallOverrides): Promise<[string]>;

    logFork(overrides?: CallOverrides): Promise<[void]>;

    performDelivery(
      numVaas: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    relayerSource(overrides?: CallOverrides): Promise<[string]>;

    relayerTarget(overrides?: CallOverrides): Promise<[string]>;

    setUp(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setUpSource(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setUpTarget(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    sourceChain(overrides?: CallOverrides): Promise<[number]>;

    sourceFork(overrides?: CallOverrides): Promise<[BigNumber]>;

    targetArtifactSelectors(
      overrides?: CallOverrides
    ): Promise<
      [StdInvariant.FuzzSelectorStructOutput[]] & {
        targetedArtifactSelectors_: StdInvariant.FuzzSelectorStructOutput[];
      }
    >;

    targetArtifacts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { targetedArtifacts_: string[] }>;

    targetChain(overrides?: CallOverrides): Promise<[number]>;

    targetContracts(
      overrides?: CallOverrides
    ): Promise<[string[]] & { targetedContracts_: string[] }>;

    targetFork(overrides?: CallOverrides): Promise<[BigNumber]>;

    targetSelectors(
      overrides?: CallOverrides
    ): Promise<
      [StdInvariant.FuzzSelectorStructOutput[]] & {
        targetedSelectors_: StdInvariant.FuzzSelectorStructOutput[];
      }
    >;

    targetSenders(
      overrides?: CallOverrides
    ): Promise<[string[]] & { targetedSenders_: string[] }>;

    tokenBridgeSource(overrides?: CallOverrides): Promise<[string]>;

    tokenBridgeTarget(overrides?: CallOverrides): Promise<[string]>;

    wormholeSource(overrides?: CallOverrides): Promise<[string]>;

    wormholeTarget(overrides?: CallOverrides): Promise<[string]>;
  };

  CELO_URL(overrides?: CallOverrides): Promise<string>;

  FUJI_URL(overrides?: CallOverrides): Promise<string>;

  IS_TEST(overrides?: CallOverrides): Promise<boolean>;

  createAndAttestToken(
    fork: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  excludeArtifacts(overrides?: CallOverrides): Promise<string[]>;

  excludeContracts(overrides?: CallOverrides): Promise<string[]>;

  excludeSenders(overrides?: CallOverrides): Promise<string[]>;

  failed(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  guardianSource(overrides?: CallOverrides): Promise<string>;

  guardianTarget(overrides?: CallOverrides): Promise<string>;

  logFork(overrides?: CallOverrides): Promise<void>;

  performDelivery(
    numVaas: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  relayerSource(overrides?: CallOverrides): Promise<string>;

  relayerTarget(overrides?: CallOverrides): Promise<string>;

  setUp(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setUpSource(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setUpTarget(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  sourceChain(overrides?: CallOverrides): Promise<number>;

  sourceFork(overrides?: CallOverrides): Promise<BigNumber>;

  targetArtifactSelectors(
    overrides?: CallOverrides
  ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

  targetArtifacts(overrides?: CallOverrides): Promise<string[]>;

  targetChain(overrides?: CallOverrides): Promise<number>;

  targetContracts(overrides?: CallOverrides): Promise<string[]>;

  targetFork(overrides?: CallOverrides): Promise<BigNumber>;

  targetSelectors(
    overrides?: CallOverrides
  ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

  targetSenders(overrides?: CallOverrides): Promise<string[]>;

  tokenBridgeSource(overrides?: CallOverrides): Promise<string>;

  tokenBridgeTarget(overrides?: CallOverrides): Promise<string>;

  wormholeSource(overrides?: CallOverrides): Promise<string>;

  wormholeTarget(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    CELO_URL(overrides?: CallOverrides): Promise<string>;

    FUJI_URL(overrides?: CallOverrides): Promise<string>;

    IS_TEST(overrides?: CallOverrides): Promise<boolean>;

    createAndAttestToken(
      fork: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    excludeArtifacts(overrides?: CallOverrides): Promise<string[]>;

    excludeContracts(overrides?: CallOverrides): Promise<string[]>;

    excludeSenders(overrides?: CallOverrides): Promise<string[]>;

    failed(overrides?: CallOverrides): Promise<boolean>;

    guardianSource(overrides?: CallOverrides): Promise<string>;

    guardianTarget(overrides?: CallOverrides): Promise<string>;

    logFork(overrides?: CallOverrides): Promise<void>;

    performDelivery(
      numVaas: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    relayerSource(overrides?: CallOverrides): Promise<string>;

    relayerTarget(overrides?: CallOverrides): Promise<string>;

    setUp(overrides?: CallOverrides): Promise<void>;

    setUpSource(overrides?: CallOverrides): Promise<void>;

    setUpTarget(overrides?: CallOverrides): Promise<void>;

    sourceChain(overrides?: CallOverrides): Promise<number>;

    sourceFork(overrides?: CallOverrides): Promise<BigNumber>;

    targetArtifactSelectors(
      overrides?: CallOverrides
    ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

    targetArtifacts(overrides?: CallOverrides): Promise<string[]>;

    targetChain(overrides?: CallOverrides): Promise<number>;

    targetContracts(overrides?: CallOverrides): Promise<string[]>;

    targetFork(overrides?: CallOverrides): Promise<BigNumber>;

    targetSelectors(
      overrides?: CallOverrides
    ): Promise<StdInvariant.FuzzSelectorStructOutput[]>;

    targetSenders(overrides?: CallOverrides): Promise<string[]>;

    tokenBridgeSource(overrides?: CallOverrides): Promise<string>;

    tokenBridgeTarget(overrides?: CallOverrides): Promise<string>;

    wormholeSource(overrides?: CallOverrides): Promise<string>;

    wormholeTarget(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "log(string)"(arg0?: null): logEventFilter;
    log(arg0?: null): logEventFilter;

    "log_address(address)"(arg0?: null): log_addressEventFilter;
    log_address(arg0?: null): log_addressEventFilter;

    "log_array(uint256[])"(val?: null): log_array_uint256_array_EventFilter;
    "log_array(int256[])"(val?: null): log_array_int256_array_EventFilter;
    "log_array(address[])"(val?: null): log_array_address_array_EventFilter;

    "log_bytes(bytes)"(arg0?: null): log_bytesEventFilter;
    log_bytes(arg0?: null): log_bytesEventFilter;

    "log_bytes32(bytes32)"(arg0?: null): log_bytes32EventFilter;
    log_bytes32(arg0?: null): log_bytes32EventFilter;

    "log_int(int256)"(arg0?: null): log_intEventFilter;
    log_int(arg0?: null): log_intEventFilter;

    "log_named_address(string,address)"(
      key?: null,
      val?: null
    ): log_named_addressEventFilter;
    log_named_address(key?: null, val?: null): log_named_addressEventFilter;

    "log_named_array(string,uint256[])"(
      key?: null,
      val?: null
    ): log_named_array_string_uint256_array_EventFilter;
    "log_named_array(string,int256[])"(
      key?: null,
      val?: null
    ): log_named_array_string_int256_array_EventFilter;
    "log_named_array(string,address[])"(
      key?: null,
      val?: null
    ): log_named_array_string_address_array_EventFilter;

    "log_named_bytes(string,bytes)"(
      key?: null,
      val?: null
    ): log_named_bytesEventFilter;
    log_named_bytes(key?: null, val?: null): log_named_bytesEventFilter;

    "log_named_bytes32(string,bytes32)"(
      key?: null,
      val?: null
    ): log_named_bytes32EventFilter;
    log_named_bytes32(key?: null, val?: null): log_named_bytes32EventFilter;

    "log_named_decimal_int(string,int256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;
    log_named_decimal_int(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;

    "log_named_decimal_uint(string,uint256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;
    log_named_decimal_uint(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;

    "log_named_int(string,int256)"(
      key?: null,
      val?: null
    ): log_named_intEventFilter;
    log_named_int(key?: null, val?: null): log_named_intEventFilter;

    "log_named_string(string,string)"(
      key?: null,
      val?: null
    ): log_named_stringEventFilter;
    log_named_string(key?: null, val?: null): log_named_stringEventFilter;

    "log_named_uint(string,uint256)"(
      key?: null,
      val?: null
    ): log_named_uintEventFilter;
    log_named_uint(key?: null, val?: null): log_named_uintEventFilter;

    "log_string(string)"(arg0?: null): log_stringEventFilter;
    log_string(arg0?: null): log_stringEventFilter;

    "log_uint(uint256)"(arg0?: null): log_uintEventFilter;
    log_uint(arg0?: null): log_uintEventFilter;

    "logs(bytes)"(arg0?: null): logsEventFilter;
    logs(arg0?: null): logsEventFilter;
  };

  estimateGas: {
    CELO_URL(overrides?: CallOverrides): Promise<BigNumber>;

    FUJI_URL(overrides?: CallOverrides): Promise<BigNumber>;

    IS_TEST(overrides?: CallOverrides): Promise<BigNumber>;

    createAndAttestToken(
      fork: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    excludeArtifacts(overrides?: CallOverrides): Promise<BigNumber>;

    excludeContracts(overrides?: CallOverrides): Promise<BigNumber>;

    excludeSenders(overrides?: CallOverrides): Promise<BigNumber>;

    failed(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    guardianSource(overrides?: CallOverrides): Promise<BigNumber>;

    guardianTarget(overrides?: CallOverrides): Promise<BigNumber>;

    logFork(overrides?: CallOverrides): Promise<BigNumber>;

    performDelivery(
      numVaas: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    relayerSource(overrides?: CallOverrides): Promise<BigNumber>;

    relayerTarget(overrides?: CallOverrides): Promise<BigNumber>;

    setUp(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    setUpSource(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    setUpTarget(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    sourceChain(overrides?: CallOverrides): Promise<BigNumber>;

    sourceFork(overrides?: CallOverrides): Promise<BigNumber>;

    targetArtifactSelectors(overrides?: CallOverrides): Promise<BigNumber>;

    targetArtifacts(overrides?: CallOverrides): Promise<BigNumber>;

    targetChain(overrides?: CallOverrides): Promise<BigNumber>;

    targetContracts(overrides?: CallOverrides): Promise<BigNumber>;

    targetFork(overrides?: CallOverrides): Promise<BigNumber>;

    targetSelectors(overrides?: CallOverrides): Promise<BigNumber>;

    targetSenders(overrides?: CallOverrides): Promise<BigNumber>;

    tokenBridgeSource(overrides?: CallOverrides): Promise<BigNumber>;

    tokenBridgeTarget(overrides?: CallOverrides): Promise<BigNumber>;

    wormholeSource(overrides?: CallOverrides): Promise<BigNumber>;

    wormholeTarget(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    CELO_URL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    FUJI_URL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    IS_TEST(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createAndAttestToken(
      fork: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    excludeArtifacts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excludeContracts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    excludeSenders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    failed(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    guardianSource(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    guardianTarget(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    logFork(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    performDelivery(
      numVaas: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    relayerSource(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    relayerTarget(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setUp(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setUpSource(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setUpTarget(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    sourceChain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sourceFork(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetArtifactSelectors(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    targetArtifacts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetChain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetContracts(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetFork(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetSelectors(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    targetSenders(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenBridgeSource(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenBridgeTarget(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wormholeSource(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wormholeTarget(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
